version: '3.8'

services:
  db:
    container_name: db-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data volume
    ports:
      - '5432:5432'
volumes:
  postgres_data:
